[Unit]
Requires=igrf-data-init.service
After=igrf-data-init.service

[Service]
ExecStartPre=
ExecStartPre=/usr/lib/igrf/ssh-keys.sh
ExecStart=
ExecStart=/usr/sbin/sshd -D -e -f /etc/ssh/sshd_config_igrf
