d /data/igrf 0700 igrf igrf -
d /data/igrf/logs 0700 igrf igrf -
d /data/ssh 0700 root root -
d /data/NetworkManager 0700 root root -
d /data/NetworkManager/system-connections 0700 root root -
d /data/NetworkManager/state 0700 root root -
