[Unit]
Requires=igrf-data-init.service igrf-x11-session.service
After=igrf-data-init.service igrf-x11-session.service

[Service]
Environment=HOME=/data/igrf
Environment=XAUTHORITY=/run/igrf-x11/Xauthority
Environment=DBUS_SESSION_BUS_ADDRESS=unix:path=/run/igrf-x11/bus
