[main]
plugins=keyfile
dhcp=internal
auth-polkit=true
dns=default
rc-manager=unmanaged
systemd-resolved=false

[device-igrf]
match-device=interface-name:eth0;interface-name:wlan0
managed=1
wifi.backend=wpa_supplicant

[connectivity]
enabled=false
